spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/Desktop/jin/Study/git/DailyStudy/h2/jpashop;MVCC=TRUE
    uesrname: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
logging:
  level:
    org.hibernate.SQL: debug
